compatibility_date = "2023-08-21"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "market-monitor"
database_id = "05a5e71a-c328-4ca0-afd0-84171706d16d"
preview_database_id = "local-test-db"

