export type QuandlData = {
  id: number;
  dataset_code: string;
  database_code: string;
  name: string;
  description: string;
  refreshed_at: string;
  newest_available_date: string;
  oldest_available_date: string;
  column_names: string[];
  frequency: string;
  type: string;
  premium: boolean;
  limit: any;
  transform: any;
  column_index: any;
  start_date: string;
  end_date: string;
  //  ['2022-04-20', 42, 10, 20, 30];
  data: [string, number, ...number[]];
};
