export type HistoricalLoadingPeriods = '1min' | '5min' | '1hour' | '4hour' | '1day' | '1week' | '1month';

export const SYMBOL_SP500 = '^GSPC';

export const MARKET_OVERVIEW_DATA = [
  {
    name: 'S&P 500',
    key: 'sp500',
    data: [
      {
        endpoint: 'MULTPL/SP500_PE_RATIO_MONTH',
        name: 'S&P 500 - PE ratio',
        databaseKey: 'qundal_sp_500_pe_ratio_by_month_value',
        provider: 'quandl',
      },
      {
        endpoint: 'MULTPL/SHILLER_PE_RATIO_MONTH',
        name: 'S&P 500 - Shiller PE',
        databaseKey: 'qundal_shiller_pe_ratio_by_month_value',
        provider: 'quandl',
      },
      {
        endpoint: 'MULTPL/SP500_BVPS_QUARTER',
        name: 'S&P 500 - Book value',
        databaseKey: 'qundal_sp_500_book_value_per_share_by_quarter_value',
        provider: 'quandl',
      },
      {
        endpoint: 'MULTPL/SP500_PBV_RATIO_QUARTER',
        name: 'S&P 500 - Price to book',
        databaseKey: 'qundal_sp_500_price_to_book_value_by_quarter_value',
        provider: 'quandl',
      },
      {
        endpoint: 'MULTPL/SP500_REAL_SALES_QUARTER',
        name: 'S&P 500 - Sales',
        databaseKey: 'qundal_sp_500_real_sales_by_quarter_value',
        provider: 'quandl',
      },
      {
        endpoint: 'MULTPL/SP500_REAL_SALES_GROWTH_QUARTER',
        name: 'S&P 500 - Sales growth',
        databaseKey: 'qundal_sp_500_real_sales_growth_by_quarter_value',
        provider: 'quandl',
      },
      {
        endpoint: 'MULTPL/SP500_PSR_QUARTER',
        name: 'S&P 500 - Price to sale',
        databaseKey: 'qundal_sp_500_price_to_sales_ratio_by_quarter_value',
        provider: 'quandl',
      },
      {
        endpoint: 'MULTPL/SP500_EARNINGS_MONTH',
        name: 'S&P 500 - Earnings',
        databaseKey: 'qundal_sp_500_earnings_by_month_value',
        provider: 'quandl',
      },
      {
        endpoint: 'MULTPL/SP500_EARNINGS_GROWTH_QUARTER',
        name: 'S&P 500 - Earnings growth',
        databaseKey: 'qundal_sp_500_earnings_growth_rate_by_quarter_value',
        provider: 'quandl',
      },
      {
        endpoint: 'MULTPL/SP500_EARNINGS_YIELD_MONTH',
        name: 'S&P 500 - Earnings yield',
        databaseKey: 'qundal_sp_500_earnings_yield_by_month_value',
        provider: 'quandl',
      },
      {
        endpoint: 'MULTPL/SP500_DIV_YIELD_MONTH',
        name: 'S&P 500 - Dividend yield',
        databaseKey: 'qundal_sp_500_dividend_yield_by_month_value',
        provider: 'quandl',
      },
      {
        endpoint: 'MULTPL/SP500_DIV_MONTH',
        name: 'S&P 500 - Dividends',
        databaseKey: 'qundal_sp_500_dividend_by_month_value',
        provider: 'quandl',
      },
      {
        endpoint: 'MULTPL/SP500_DIV_GROWTH_QUARTER',
        name: 'S&P 500 - Dividend growth',
        databaseKey: 'qundal_sp_500_dividend_growth_by_quarter_value',
        provider: 'quandl',
      },
    ],
  },
  {
    name: 'Bonds',
    key: 'bonds',
    data: [
      {
        endpoint: 'ML/AAAEY',
        name: 'Bond - US AAA yield',
        databaseKey: 'qundal_us_aaa_rated_bond_index_yield_bamlc0a1caaaey',
        provider: 'quandl',
      },
      {
        endpoint: 'ML/AAY',
        name: 'Bond - US AA yield',
        databaseKey: 'qundal_us_aa_bond_index_yield_bamlc0a2caaey',
        provider: 'quandl',
      },
      {
        endpoint: 'ML/AEY',
        name: 'Bond - US A yield',
        databaseKey: 'qundal_us_corporate_bond_a_rated_index_yield_bamlc0a3caey',
        provider: 'quandl',
      },
      {
        endpoint: 'ML/BBY',
        name: 'Bond - US BB yield',
        databaseKey: 'qundal_us_high_yield_bb_corporate_bond_index_yield_bamlh0a1hybbey',
        provider: 'quandl',
      },
      {
        endpoint: 'ML/BEY',
        name: 'Bond - US B yield',
        databaseKey: 'qundal_us_b_rated_corporate_bond_index_yield_bamlh0a2hybey',
        provider: 'quandl',
      },
      {
        endpoint: 'ML/CCCY',
        name: 'Bond - US CCC yield',
        databaseKey: 'qundal_us_cccrated_bond_index_yield_bamlh0a3hycey',
        provider: 'quandl',
      },
      {
        endpoint: 'ML/USEY',
        name: 'Bond - US yield',
        databaseKey: 'qundal_us_corporate_bond_index_yield_bamlc0a0cmey',
        provider: 'quandl',
      },
      {
        endpoint: 'ML/USTRI',
        name: 'Bond - US high yield',
        databaseKey: 'qundal_us_high_yield_corporate_bond_index_yield_bamlh0a0hym2ey',
        provider: 'quandl',
      },
      {
        endpoint: 'ML/EEMCBI',
        name: 'Bond - Euro emerging markets yield',
        databaseKey: 'qundal_euro_emerging_markets_corporate_bond_index_yield_bamlemebcrpieey',
        provider: 'quandl',
      },
      {
        endpoint: 'ML/EMHYY',
        name: 'Bond - Emerging markets high yield',
        databaseKey: 'qundal_emerging_markets_high_yield_corporate_bond_index_yield_bamlemhbhycrpiey',
        provider: 'quandl',
      },
    ],
  },
  {
    name: 'Treasury yield',
    key: 'treasury_yield',
    data: [
      {
        endpoint: 'USTREASURY/YIELD',
        name: 'Treasury yield 1 MO',
        databaseKey: 'qundal_treasury_yield_curve_rates_1_mo',
        provider: 'quandl',
      },
      {
        endpoint: 'USTREASURY/YIELD',
        name: 'Treasury yield 2 MO',
        databaseKey: 'qundal_treasury_yield_curve_rates_2_mo',
        provider: 'quandl',
      },
      {
        endpoint: 'USTREASURY/YIELD',
        name: 'Treasury yield 3 MO',
        databaseKey: 'qundal_treasury_yield_curve_rates_3_mo',
        provider: 'quandl',
      },
      {
        endpoint: 'USTREASURY/YIELD',
        name: 'Treasury yield 6 MO',
        databaseKey: 'qundal_treasury_yield_curve_rates_6_mo',
        provider: 'quandl',
      },
      {
        endpoint: 'USTREASURY/YIELD',
        name: 'Treasury yield 1 YR',
        databaseKey: 'qundal_treasury_yield_curve_rates_1_yr',
        provider: 'quandl',
      },
      {
        endpoint: 'USTREASURY/YIELD',
        name: 'Treasury yield 2 YR',
        databaseKey: 'qundal_treasury_yield_curve_rates_2_yr',
        provider: 'quandl',
      },
      {
        endpoint: 'USTREASURY/YIELD',
        name: 'Treasury yield 3 YR',
        databaseKey: 'qundal_treasury_yield_curve_rates_2_yr',
        provider: 'quandl',
      },
      {
        endpoint: 'USTREASURY/YIELD',
        name: 'Treasury yield 5 YR',
        databaseKey: 'qundal_treasury_yield_curve_rates_5_yr',
        provider: 'quandl',
      },
      {
        endpoint: 'USTREASURY/YIELD',
        name: 'Treasury yield 7 YR',
        databaseKey: 'qundal_treasury_yield_curve_rates_7_yr',
        provider: 'quandl',
      },
      {
        endpoint: 'USTREASURY/YIELD',
        name: 'Treasury yield 10 YR',
        databaseKey: 'qundal_treasury_yield_curve_rates_10_yr',
        provider: 'quandl',
      },
      {
        endpoint: 'USTREASURY/YIELD',
        name: 'Treasury yield 20 YR',
        databaseKey: 'qundal_treasury_yield_curve_rates_20_yr',
        provider: 'quandl',
      },
      {
        endpoint: 'USTREASURY/YIELD',
        name: 'Treasury yield 30 YR',
        databaseKey: 'qundal_treasury_yield_curve_rates_30_yr',
        provider: 'quandl',
      },
    ],
  },
  {
    name: 'Consumer price index states',
    key: 'consumer_price_index_states',
    data: [
      {
        endpoint: 'RATEINF/CPI_USA',
        name: 'Consumer price index - USA',
        databaseKey: 'qundal_consumer_price_index__usa_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/CPI_EUR',
        name: 'Consumer price index - Europe',
        databaseKey: 'qundal_consumer_price_index__euro_area_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/CPI_GBR',
        name: 'Consumer price index - UK',
        databaseKey: 'qundal_consumer_price_index__uk_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/CPI_JPN',
        name: 'Consumer price index - Japan',
        databaseKey: 'qundal_consumer_price_index__japan_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/CPI_CAN',
        name: 'Consumer price index - Canada',
        databaseKey: 'qundal_consumer_price_index__canada_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/CPI_CHE',
        name: 'Consumer price index - Switzerland',
        databaseKey: 'qundal_consumer_price_index__switzerland_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/CPI_RUS',
        name: 'Consumer price index - Russia',
        databaseKey: 'qundal_consumer_price_index__russia_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/CPI_AUS',
        name: 'Consumer price index - Australia',
        databaseKey: 'qundal_consumer_price_index__australia_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/CPI_DEU',
        name: 'Consumer price index - Germany',
        databaseKey: 'qundal_consumer_price_index__germany_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/CPI_FRA',
        name: 'Consumer price index - France',
        databaseKey: 'qundal_consumer_price_index__france_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/CPI_ITA',
        name: 'Consumer price index - Italy',
        databaseKey: 'qundal_consumer_price_index__italy_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/CPI_NZL',
        name: 'Consumer price index - New Zealand',
        databaseKey: 'qundal_consumer_price_index__new_zealand_value',
        provider: 'quandl',
      },
    ],
  },
  {
    name: 'Inflation rate',
    key: 'inflation_rate',
    data: [
      {
        endpoint: 'RATEINF/INFLATION_USA',
        name: 'Inflation YOY - USA',
        databaseKey: 'qundal_inflation_yoy__usa_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/INFLATION_EUR',
        name: 'Inflation YOY - Europe',
        databaseKey: 'qundal_inflation_yoy__euro_area_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/INFLATION_GBR',
        name: 'Inflation YOY - UK',
        databaseKey: 'qundal_inflation_yoy__uk_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/INFLATION_CAN',
        name: 'Inflation YOY - Canada',
        databaseKey: 'qundal_inflation_yoy__canada_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/INFLATION_JPN',
        name: 'Inflation YOY - Japan',
        databaseKey: 'qundal_inflation_yoy__japan_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/INFLATION_CHE',
        name: 'Inflation YOY - Switzerland',
        databaseKey: 'qundal_inflation_yoy__switzerland_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/INFLATION_RUS',
        name: 'Inflation YOY - Russia',
        databaseKey: 'qundal_inflation_yoy__russia_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/INFLATION_AUS',
        name: 'Inflation YOY - Australia',
        databaseKey: 'qundal_inflation_yoy__australia_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/INFLATION_ARG',
        name: 'Inflation YOY - Argentina',
        databaseKey: 'qundal_inflation_yoy__argentina_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/INFLATION_DEU',
        name: 'Inflation YOY - Germany',
        databaseKey: 'qundal_inflation_yoy__germany_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/INFLATION_FRA',
        name: 'Inflation YOY - France',
        databaseKey: 'qundal_inflation_yoy__france_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/INFLATION_ITA',
        name: 'Inflation YOY - Italy',
        databaseKey: 'qundal_inflation_yoy__italy_value',
        provider: 'quandl',
      },
      {
        endpoint: 'RATEINF/INFLATION_NZL',
        name: 'Inflation YOY - New Zealand',
        databaseKey: 'qundal_inflation_yoy__new_zealand_value',
        provider: 'quandl',
      },
    ],
  },
  {
    name: 'Bitcoin',
    key: 'bitcoin',
    data: [
      {
        endpoint: 'BCHAIN/MKTCP',
        name: 'Market cap',
        databaseKey: 'qundal_bitcoin_market_capitalization_value',
        provider: 'quandl',
      },
      {
        endpoint: 'BCHAIN/TRVOU',
        name: 'Traiding volume',
        databaseKey: 'qundal_bitcoin_usd_exchange_trade_volume_value',
        provider: 'quandl',
      },
      {
        endpoint: 'BCHAIN/TRFUS',
        name: 'Transaction fees',
        databaseKey: 'qundal_bitcoin_total_transaction_fees_usd_value',
        provider: 'quandl',
      },
      {
        endpoint: 'BCHAIN/ATRCT',
        name: 'Transaction time',
        databaseKey: 'qundal_bitcoin_median_transaction_confirmation_time_value',
        provider: 'quandl',
      },
      {
        endpoint: 'BCHAIN/CPTRA',
        name: 'Transaction cost',
        databaseKey: 'qundal_bitcoin_cost_per_transaction_value',
        provider: 'quandl',
      },
      {
        endpoint: 'BCHAIN/NTRAN',
        name: 'Daily transactions',
        databaseKey: 'qundal_bitcoin_number_of_transactions_value',
        provider: 'quandl',
      },
    ],
  },
] as const;
