import * as admin from 'firebase-admin';
import { onRequest } from 'firebase-functions/v2/https';
import { DATABASE_URL } from './environment';

// Start writing Firebase Functions
// https://firebase.google.com/docs/functions/typescript
// eslint-disable-next-line @typescript-eslint/no-var-requires
const serviceAccount = require('../firebase_key.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: DATABASE_URL,
});

export const helloWorld = onRequest((request, response) => {
  response.send('Hello from Firebase - Generated by @nx-toolkits/firebase!');
});
